name: Create PR for release
# Pushes a tag whenever the version in package.json changes and creates a github release
# This is triggered only when a Pull Request is merged to master and version in package json changes

on:
  push:
    branches:
      - 'release_v*.*.*'
    paths:
      - 'gradle.properties'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4