on:
  pull_request:
    branches:
      - master
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Create a tag
        id: create_tag
        uses: Klemensas/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_prefix: "v"
      - name: Create a Release
        uses: ncipollo/release-action@v1
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        with:  
          tag: ${{ steps.create_tag.outputs.tagname }}