name: Create PR for release
# Pushes a tag whenever the version in package.json changes and creates a github release
# This is triggered only when a Pull Request is merged to master and version in package json changes

on:
  create:
    branches:
      - 'release_v*.*.*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/release_v') }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}